name: "Isort"
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
jobs:
  isort:
    strategy:
      matrix:
        python-version: [ "3.8.1", "3.9", "3.10" ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Run poetry install
      run: |
        poetry install --only=dev
    - name: Run isort
      run: |
        poetry run isort mapd/ tests/