name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install poetry
      run: |
        pipx install poetry
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Poetry install
      run: poetry install
    - name: Use Python Semantic Release to prepare release
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        poetry build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        skip_existing: true
